### ISSUE TITLE
Experiência do usuário: Adicionar um texto de introdução da seção

### ISSUE THREAD

**Issue by luizfsborges** [2023M8T2-Inteli/grupo2#15]

**Comment by edu-porto** [comment]
Resolvido https://github.com/2023M8T2-Inteli/grupo2/commit/42cfbc39427e4bdcdf5687aad208ee76892ab34d 

Link, do docussaurus https://2023m8t2-inteli.github.io/grupo2/sprint1/Entendimento%20da%20experi%C3%AAncia%20do%20usu%C3%A1rio/
