### ISSUE TITLE
Fechamento de Issues (Tarefas)

### ISSUE THREAD

**Issue by Murilo-ZC** [2023M8T2-Inteli/grupo2#3]
Pessoal quando uma tarefa for fechada, quando ela estiver concluída, ela deve necessariamente estar vinculada a um commit que demonstra como ela fechou. Por exemplo eu fui verificar o commit de matriz de valor que estava fechado e não tinha nada no repositório. Descrever o porque a Issue foi fechada.

**Comment by edu-porto** [comment]
já foi arrumado
