### ISSUE TITLE
Documento sobre análise ética - introdução e estrutura

### ISSUE THREAD

**Issue by Murilo-ZC** [2023M8T2-Inteli/grupo2#4]
O objetivo do projeto é construir um AMR como um robô de serviço. Fazer essa correção. O primeiro paragrafo tem apenas uma frase. Fazer uma separação. 
Tomar cuidado em organizar a forma como os dados estão no documento, não deixar de levar eles para a versão consolidada na documentação.
Em equidade e justiça, parece um conjunto de regras e não uma analise. O mesmo vale para Transparência e Consentimento. Como o projeto vai auxiliar na redução de desperdício? Isso não está claro aqui. Em Viés e Discriminação senti o mesmo ponto. Sugestão: revisar o documento e já iniciar sua consolidação.

**Comment by edu-porto** [comment]
já foi arrumado

**Comment by amandafontes** [comment]
Análise de impacto ético atualizada, disponível via commit #cafbeb209f03eeb4a53993822531a926789b01bc
