### ISSUE TITLE
Analise Financeira

### ISSUE THREAD

**Issue by Murilo-ZC** [2023M8T2-Inteli/grupo2#8]
Adicionar o custo do rolo de filamento mesmo e de realizar a impressão 3D. Eu colocaria o custo de uma impressora 3D (creality k1 como referência) mais uns 10% para variação do preço. Não é exatamente igual, mas pode considerar que o Mecatrônico e o de Controle e Automação vão fazer a mesma função. Adicionar o custo de utilizar uma API como a do ChatGPT só por referência de custo de uso de uma LLM comercial.

**Comment by edu-porto** [comment]
já foi arrumado

**Comment by amandafontes** [comment]
Análise financeira atualizada, disponível no commit #f7d1ed662a666de488481f7316d1a2e7649f159a
