### ISSUE TITLE
Matriz oceano Azul

### ISSUE THREAD

**Issue by Murilo-ZC** [2023M8T2-Inteli/grupo2#9]
Quanto tem a matriz, o que indica cada uma das linhas? Um paragrafo ou dois explicando ela, que vira speech na apresentação acho que pode ser bem rico nessa sprint em especial

**Comment by edu-porto** [comment]
já foi arrumado

**Comment by amandafontes** [comment]
Matriz de oceano azul atualizada via commit #baa1650ab717b9b71a41a9ad0324efc6c12747ac
